plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'org.writer'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
}

test {
    useJUnitPlatform()
}

// Для публикации библиотеки
publishing {
    publications {
        maven(MavenPublication) {
            from components.java

            groupId = 'org.writer'
            artifactId = 'csv'
            version = '1.0-SNAPSHOT'
        }
    }

    repositories {
        maven {
            name = 'localRepo'
            url = uri("${buildDir}/repo")
        }
    }
}